name:                parser-combinators
version:             0.1.0.0
github:              "ssanj/parser-combinators"
license:             BSD3
author:              "sanjiv sahayam"
maintainer:          "sanjsmailbox@gmail.com"
copyright:           "(c) 2017 sanjiv sahayam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ssanj/parser-combinators#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  parser-combinators-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parser-combinators

tests:
  parser-combinators-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parser-combinators
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-hedgehog
    - hedgehog
